---
# ConfigMap for auth-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "5001"
  MONGO_URI: "mongodb+srv://evolvifiers:password_123@cluster0.r7dfn.mongodb.net/users?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "evolvifiers"
  JWT_EXPIRES_IN: "360000"
---
# ConfigMap for train-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: train-service-config
data:
  PORT: "5002"
  MONGO_URI: "mongodb+srv://evolvifiers:password_123@cluster0.r7dfn.mongodb.net/trains?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "evolvifiers"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://rabbitmq"
---
# ConfigMap for booking-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-config
data:
  PORT: "5003"
  MONGO_URI: "mongodb+srv://evolvifiers:password_123@cluster0.r7dfn.mongodb.net/booking?retryWrites=true&w=majority&appName=Cluster0"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://rabbitmq"
  JWT_SECRET: "evolvifiers"
---
# ConfigMap for payment-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "5004"
  MONGO_URI: "mongodb+srv://evolvifiers:password_123@cluster0.r7dfn.mongodb.net/payments?retryWrites=true&w=majority&appName=Cluster0"
  RABBITMQ_URL: "amqp://rabbitmq"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "asifmahmoud414@gmail.com"
  SMTP_PASS: "fqqf vqsn bwrg hcak"
  OTP_SECRET: "evolvifiers"
---
# ConfigMap for api-gateway
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "5000"
  AUTH_SERVICE_URL: "http://auth-service:5001"
  TRAIN_SERVICE_URL: "http://train-service:5002"
  BOOKING_SERVICE_URL: "http://booking-service:5003"
  TICKET_SERVICE_URL: "http://ticket-service:5004"