---
- name: Install K3s master
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server --node-external-ip {{ ansible_host }}
  become: true

- name: Fetch K3s token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  become: true

- name: Save token for workers
  set_fact:
    k3s_token: "{{ k3s_token.stdout }}"
