name: Auth Service CI/CD
on:
  push:
    branches:
      - main
    paths:
      - services/auth-service/**
  pull_request:
    branches:
      - main
    paths:
      - services/auth-service/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth-service
          push: true
          tags: fazlulkarim105925/auth-service:latest
      
      - name: Logout from Docker Hub
        run: docker logout

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.MASTER_IP }} >> ~/.ssh/known_hosts
      
      - name: Copy manifest files to Kubernetes master node
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no Manifests/configmaps.yaml ubuntu@${{ secrets.MASTER_IP }}:/home/ubuntu/Manifests/
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no Manifests/deployments.yaml ubuntu@${{ secrets.MASTER_IP }}:/home/ubuntu/Manifests/
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no Manifests/services.yaml ubuntu@${{ secrets.MASTER_IP }}:/home/ubuntu/Manifests/
      
      - name: Deploy to Kubernetes
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.MASTER_IP }} "cd /home/ubuntu/Manifests && \
          kubectl apply -f configmaps.yaml && \
          kubectl apply -f deployments.yaml && \
          kubectl apply -f services.yaml"
      
      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.MASTER_IP }} "kubectl get pods"