name: Booking Service CI/CD
on:
  push:
    branches:
      - main
    paths:
      - services/booking-service/**
  pull_request:
    branches:
      - main
    paths:
      - services/booking-service/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/booking-service
          push: true
          tags: fazlulkarim105925/booking-service:${{ github.run_number }}
      
      - name: Logout from Docker Hub
        run: docker logout

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key